CREATE TABLE `assets` (
  `Asset_Id` int NOT NULL,
  `Asset_Name` varchar(30) DEFAULT NULL,
  `Barcode` varchar(13) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Brand_Name` varchar(30) DEFAULT NULL,
  `warranty` varchar(3) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Location` varchar(30) DEFAULT NULL,
  `Owner` varchar(34) DEFAULT NULL,
  `Value` decimal(10,0) DEFAULT NULL,
  `AssetCondition` varchar(45) DEFAULT NULL,
  `Supplier` varchar(20) DEFAULT NULL,
  `Qty` int DEFAULT NULL,
  `OrderedDate` datetime DEFAULT NULL,
  `DeliveredDate` datetime DEFAULT NULL,
  `ExcessQty` int DEFAULT NULL,
  `AssetTypeID` int NOT NULL,
  PRIMARY KEY (`Asset_Id`),
  KEY `AssetTypeID_idx` (`AssetTypeID`),
  CONSTRAINT `AssetTypeID` FOREIGN KEY (`AssetTypeID`) REFERENCES `assettype` (`AssetTypeID`)
)