CREATE TABLE `vacancies` (
  `Job_refNo` varchar(233) NOT NULL,
  `Position` varchar(20) DEFAULT NULL,
  `DepID` int NOT NULL,
  `ContractId` int DEFAULT NULL,
  `JobDescription` varchar(255) DEFAULT NULL,
  `OpenDate` date DEFAULT NULL,
  `ClosingDate` date DEFAULT NULL,
  `Duration` varchar(20) DEFAULT NULL,
  `PayId` int DEFAULT NULL,
  `Branch_id` int DEFAULT NULL,
  `Requirement` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Job_refNo`),
  KEY `dep_idx` (`DepID`),
  KEY `pay_idx` (`PayId`),
  KEY `con_idx` (`ContractId`),
  KEY `branc_idx` (`Branch_id`),
  KEY `depV_idx` (`DepID`),
  KEY `payV_idx` (`PayId`),
  KEY `conV_idx` (`ContractId`),
  KEY `brancV_idx` (`Branch_id`),
  CONSTRAINT `brancV` FOREIGN KEY (`Branch_id`) REFERENCES `branches` (`Branch_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `conV` FOREIGN KEY (`ContractId`) REFERENCES `contracts` (`ContractId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `depV` FOREIGN KEY (`DepID`) REFERENCES `departments` (`DepId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `payV` FOREIGN KEY (`PayId`) REFERENCES `paygrades` (`PayId`) ON DELETE CASCADE ON UPDATE CASCADE
)